// CardClutch Canonical Card Catalog
// Single source of truth for all card data
// Last updated: 2025-01-03
// Card count: 50

export type CardNetwork = 'visa' | 'mastercard' | 'amex' | 'discover';
export type DataConfidence = 'high' | 'medium' | 'low';
export type ValueType = 'points' | 'cashback';

export interface CardReward {
  category: string;
  multiplier: number;
  notes?: string;
  caps?: string;
  exclusions?: string[];
}

export interface CardArtwork {
  kind: 'gradient';
  primary: string;
  secondary: string;
  accent?: string;
  pattern?: 'metallic' | 'minimal' | 'premium' | 'standard';
}

export interface Card {
  id: string;
  name: string;
  issuer: string;
  network: CardNetwork;
  annual_fee_cents: number | null;
  last_verified: string;
  rewards: CardReward[];
  exclusions: string[];
  highlights: string[];
  artwork: CardArtwork;
  foreign_tx_fee_percent: number | null;
  credits_summary?: string;
  // New fields for V2
  learnMoreUrl?: string;
  applyUrl?: string;
  issuerDomainAllowlist?: string[];
  dataConfidence: DataConfidence;
  needsVerification: boolean;
  baseEarning: string;
  valueType: ValueType;
}

export const cardCatalog: Card[] = [
  // === AMERICAN EXPRESS (10 cards) ===
  {
    id: 'amex-gold',
    name: 'Gold Card',
    issuer: 'American Express',
    network: 'amex',
    annual_fee_cents: 32500,
    last_verified: '2025-01-03',
    baseEarning: '1x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Dining', multiplier: 4, notes: 'Restaurants worldwide' },
      { category: 'U.S. Supermarkets', multiplier: 4, notes: 'Excludes warehouse clubs', caps: 'Up to $25,000/year', exclusions: ['Costco', 'Sam\'s Club', 'Walmart', 'Target'] },
      { category: 'Flights', multiplier: 3, notes: 'Booked directly with airlines or Amex Travel' },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: ['Costco', 'Sam\'s Club', 'Walmart', 'Target', 'Amazon Fresh', 'Wholesale clubs'],
    highlights: [
      '$120 Uber Cash credit annually',
      '$120 dining credit at select restaurants',
      '$100 airline fee credit',
      'No foreign transaction fees',
    ],
    artwork: { kind: 'gradient', primary: '#B8860B', secondary: '#DAA520', accent: '#FFD700', pattern: 'metallic' },
    foreign_tx_fee_percent: 0,
    credits_summary: '$120 Uber + $120 dining + $100 airline fee credits',
    learnMoreUrl: 'https://www.americanexpress.com/us/credit-cards/card/gold-card/',
    applyUrl: 'https://www.americanexpress.com/us/credit-cards/card-application/apply/gold-card/',
  },
  {
    id: 'amex-platinum',
    name: 'Platinum Card',
    issuer: 'American Express',
    network: 'amex',
    annual_fee_cents: 69500,
    last_verified: '2025-01-03',
    baseEarning: '1x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Flights (Amex Travel)', multiplier: 5, notes: 'Booked through Amex Travel portal' },
      { category: 'Flights (Direct)', multiplier: 5, notes: 'Booked directly with airlines' },
      { category: 'Hotels (Amex Travel)', multiplier: 5, notes: 'Prepaid through Amex Travel' },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      '$200 airline fee credit',
      '$200 hotel credit (Fine Hotels + Resorts)',
      '$240 digital entertainment credit',
      'Priority Pass & Centurion lounge access',
    ],
    artwork: { kind: 'gradient', primary: '#C0C0C0', secondary: '#E8E8E8', accent: '#A9A9A9', pattern: 'metallic' },
    foreign_tx_fee_percent: 0,
    credits_summary: '$200 airline + $200 hotel + $240 digital entertainment',
    learnMoreUrl: 'https://www.americanexpress.com/us/credit-cards/card/platinum/',
    applyUrl: 'https://www.americanexpress.com/us/credit-cards/card-application/apply/platinum-card/',
  },
  {
    id: 'amex-green',
    name: 'Green Card',
    issuer: 'American Express',
    network: 'amex',
    annual_fee_cents: 15000,
    last_verified: '2025-01-03',
    baseEarning: '1x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Travel', multiplier: 3, notes: 'Flights, hotels, transit, rideshare' },
      { category: 'Dining', multiplier: 3, notes: 'Restaurants worldwide' },
      { category: 'Transit', multiplier: 3, notes: 'Subway, trains, buses, rideshare' },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      '$189 CLEAR Plus credit',
      'LoungeBuddy credits',
      'No foreign transaction fees',
    ],
    artwork: { kind: 'gradient', primary: '#228B22', secondary: '#32CD32', accent: '#90EE90', pattern: 'metallic' },
    foreign_tx_fee_percent: 0,
    credits_summary: '$189 CLEAR Plus credit',
    learnMoreUrl: 'https://www.americanexpress.com/us/credit-cards/card/green/',
    applyUrl: 'https://www.americanexpress.com/us/credit-cards/card-application/apply/green-card/',
  },
  {
    id: 'amex-blue-cash-preferred',
    name: 'Blue Cash Preferred',
    issuer: 'American Express',
    network: 'amex',
    annual_fee_cents: 9500,
    last_verified: '2025-01-03',
    baseEarning: '1%',
    valueType: 'cashback',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'U.S. Supermarkets', multiplier: 6, notes: 'At U.S. supermarkets', caps: 'Up to $6,000/year, then 1%', exclusions: ['Costco', 'Sam\'s Club', 'Walmart', 'Target'] },
      { category: 'Streaming', multiplier: 6, notes: 'Select U.S. streaming subscriptions' },
      { category: 'Transit', multiplier: 3, notes: 'Including rideshare' },
      { category: 'Gas Stations', multiplier: 3, notes: 'U.S. gas stations' },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: ['Costco', 'Sam\'s Club', 'Walmart', 'Target', 'Wholesale clubs'],
    highlights: [
      'Best for grocery spending',
      'Strong streaming cashback',
      'Transit bonus category',
    ],
    artwork: { kind: 'gradient', primary: '#1E3A5F', secondary: '#2E5A8F', accent: '#4A90D9', pattern: 'standard' },
    foreign_tx_fee_percent: 2.7,
    learnMoreUrl: 'https://www.americanexpress.com/us/credit-cards/card/blue-cash-preferred/',
    applyUrl: 'https://www.americanexpress.com/us/credit-cards/card-application/apply/blue-cash-preferred-credit-card/',
  },
  {
    id: 'amex-blue-cash-everyday',
    name: 'Blue Cash Everyday',
    issuer: 'American Express',
    network: 'amex',
    annual_fee_cents: 0,
    last_verified: '2025-01-03',
    baseEarning: '1%',
    valueType: 'cashback',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'U.S. Supermarkets', multiplier: 3, caps: 'Up to $6,000/year, then 1%', exclusions: ['Costco', 'Sam\'s Club', 'Walmart', 'Target'] },
      { category: 'Gas Stations', multiplier: 3, notes: 'U.S. gas stations' },
      { category: 'Online Retail', multiplier: 3, caps: 'Up to $6,000/year, then 1%' },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: ['Costco', 'Sam\'s Club', 'Walmart', 'Target'],
    highlights: [
      'No annual fee',
      'Good everyday earner',
      'Online shopping bonus',
    ],
    artwork: { kind: 'gradient', primary: '#4169E1', secondary: '#6495ED', accent: '#87CEEB', pattern: 'standard' },
    foreign_tx_fee_percent: 2.7,
    learnMoreUrl: 'https://www.americanexpress.com/us/credit-cards/card/blue-cash-everyday/',
    applyUrl: 'https://www.americanexpress.com/us/credit-cards/card-application/apply/blue-cash-everyday-credit-card/',
  },
  {
    id: 'amex-hilton-honors',
    name: 'Hilton Honors Card',
    issuer: 'American Express',
    network: 'amex',
    annual_fee_cents: 0,
    last_verified: '2025-01-03',
    baseEarning: '3x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Hilton Properties', multiplier: 7, notes: 'At Hilton hotels worldwide' },
      { category: 'Dining', multiplier: 5, notes: 'At restaurants in the U.S.' },
      { category: 'U.S. Supermarkets', multiplier: 5 },
      { category: 'Gas Stations', multiplier: 5, notes: 'U.S. gas stations' },
      { category: 'All Other Purchases', multiplier: 3 },
    ],
    exclusions: [],
    highlights: [
      'No annual fee',
      'Automatic Hilton Silver status',
      'Good for Hilton loyalists',
    ],
    artwork: { kind: 'gradient', primary: '#002664', secondary: '#003D99', accent: '#0066CC', pattern: 'standard' },
    foreign_tx_fee_percent: 2.7,
    learnMoreUrl: 'https://www.americanexpress.com/us/credit-cards/card/hilton-honors/',
    applyUrl: 'https://www.americanexpress.com/us/credit-cards/card-application/apply/hilton-honors-credit-card/',
  },
  {
    id: 'amex-hilton-surpass',
    name: 'Hilton Honors Surpass',
    issuer: 'American Express',
    network: 'amex',
    annual_fee_cents: 15000,
    last_verified: '2025-01-03',
    baseEarning: '3x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Hilton Properties', multiplier: 12, notes: 'At Hilton hotels worldwide' },
      { category: 'Dining', multiplier: 6, notes: 'At U.S. restaurants' },
      { category: 'U.S. Supermarkets', multiplier: 6 },
      { category: 'Gas Stations', multiplier: 6, notes: 'U.S. gas stations' },
      { category: 'All Other Purchases', multiplier: 3 },
    ],
    exclusions: [],
    highlights: [
      'Automatic Hilton Gold status',
      'Free night reward annually',
      'Priority Pass Select membership',
    ],
    artwork: { kind: 'gradient', primary: '#1A1A2E', secondary: '#002664', accent: '#0066CC', pattern: 'premium' },
    foreign_tx_fee_percent: 0,
    credits_summary: 'Free night reward after $15K spend',
    learnMoreUrl: 'https://www.americanexpress.com/us/credit-cards/card/hilton-honors-surpass/',
    applyUrl: 'https://www.americanexpress.com/us/credit-cards/card-application/apply/hilton-honors-surpass-credit-card/',
  },
  {
    id: 'amex-marriott-bonvoy-brilliant',
    name: 'Marriott Bonvoy Brilliant',
    issuer: 'American Express',
    network: 'amex',
    annual_fee_cents: 65000,
    last_verified: '2025-01-03',
    baseEarning: '2x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Marriott Properties', multiplier: 6, notes: 'At participating Marriott hotels' },
      { category: 'Dining', multiplier: 3, notes: 'At restaurants worldwide' },
      { category: 'Flights', multiplier: 3, notes: 'Purchased directly from airlines' },
      { category: 'All Other Purchases', multiplier: 2 },
    ],
    exclusions: [],
    highlights: [
      'Platinum Elite status',
      '$300 dining credit annually',
      'Free night award (up to 85K points)',
      'Priority Pass Select',
    ],
    artwork: { kind: 'gradient', primary: '#8B0000', secondary: '#B22222', accent: '#CD5C5C', pattern: 'premium' },
    foreign_tx_fee_percent: 0,
    credits_summary: '$300 dining credit + free night award',
    learnMoreUrl: 'https://www.americanexpress.com/us/credit-cards/card/marriott-bonvoy-brilliant/',
    applyUrl: 'https://www.americanexpress.com/us/credit-cards/card-application/apply/marriott-bonvoy-brilliant-card/',
  },
  {
    id: 'amex-delta-skymiles-gold',
    name: 'Delta SkyMiles Gold',
    issuer: 'American Express',
    network: 'amex',
    annual_fee_cents: 15000,
    last_verified: '2025-01-03',
    baseEarning: '1x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Delta Purchases', multiplier: 2, notes: 'On Delta purchases' },
      { category: 'Dining', multiplier: 2, notes: 'At restaurants worldwide' },
      { category: 'U.S. Supermarkets', multiplier: 2 },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      'First checked bag free on Delta',
      'Priority boarding',
      'No foreign transaction fees',
    ],
    artwork: { kind: 'gradient', primary: '#003366', secondary: '#E01933', accent: '#FFFFFF', pattern: 'standard' },
    foreign_tx_fee_percent: 0,
    learnMoreUrl: 'https://www.americanexpress.com/us/credit-cards/card/delta-skymiles-gold-american-express-card/',
    applyUrl: 'https://www.americanexpress.com/us/credit-cards/card-application/apply/delta-skymiles-gold-american-express-card/',
  },
  {
    id: 'amex-delta-skymiles-platinum',
    name: 'Delta SkyMiles Platinum',
    issuer: 'American Express',
    network: 'amex',
    annual_fee_cents: 35000,
    last_verified: '2025-01-03',
    baseEarning: '1x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Delta Purchases', multiplier: 3, notes: 'On Delta purchases' },
      { category: 'Hotels', multiplier: 3, notes: 'Booked directly' },
      { category: 'Dining', multiplier: 2, notes: 'At restaurants worldwide' },
      { category: 'U.S. Supermarkets', multiplier: 2 },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      'Companion Certificate annually',
      'First checked bag free',
      'Priority boarding',
    ],
    artwork: { kind: 'gradient', primary: '#003366', secondary: '#C0C0C0', accent: '#E01933', pattern: 'premium' },
    foreign_tx_fee_percent: 0,
    credits_summary: 'Companion Certificate annually',
    learnMoreUrl: 'https://www.americanexpress.com/us/credit-cards/card/delta-skymiles-platinum-american-express-card/',
    applyUrl: 'https://www.americanexpress.com/us/credit-cards/card-application/apply/delta-skymiles-platinum-american-express-card/',
  },

  // === CHASE (8 cards) ===
  {
    id: 'chase-sapphire-preferred',
    name: 'Sapphire Preferred',
    issuer: 'Chase',
    network: 'visa',
    annual_fee_cents: 9500,
    last_verified: '2025-01-03',
    baseEarning: '1x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Travel (Chase Portal)', multiplier: 5, notes: 'Booked through Chase Travel' },
      { category: 'Dining', multiplier: 3 },
      { category: 'Streaming Services', multiplier: 3 },
      { category: 'Online Grocery', multiplier: 3, notes: 'Excludes Target, Walmart', exclusions: ['Target', 'Walmart'] },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: ['Target', 'Walmart'],
    highlights: [
      'Points worth 25% more via Chase Travel',
      'Transfer to airline/hotel partners',
      'No foreign transaction fees',
    ],
    artwork: { kind: 'gradient', primary: '#1A1F71', secondary: '#2E3A8C', accent: '#4169E1', pattern: 'premium' },
    foreign_tx_fee_percent: 0,
    learnMoreUrl: 'https://creditcards.chase.com/rewards-credit-cards/sapphire/preferred',
    applyUrl: 'https://creditcards.chase.com/a1/sapphirepreferred/compare',
  },
  {
    id: 'chase-sapphire-reserve',
    name: 'Sapphire Reserve',
    issuer: 'Chase',
    network: 'visa',
    annual_fee_cents: 55000,
    last_verified: '2025-01-03',
    baseEarning: '1x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Hotels (Chase Travel)', multiplier: 10, notes: 'Hotels & car rentals via Chase Travel' },
      { category: 'Flights (Chase Travel)', multiplier: 5, notes: 'Via Chase Travel' },
      { category: 'Dining', multiplier: 3 },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      '$300 annual travel credit',
      'Points worth 50% more via Chase Travel',
      'Priority Pass lounge access',
      'No foreign transaction fees',
    ],
    artwork: { kind: 'gradient', primary: '#0D1B2A', secondary: '#1B263B', accent: '#415A77', pattern: 'premium' },
    foreign_tx_fee_percent: 0,
    credits_summary: '$300 annual travel credit',
    learnMoreUrl: 'https://creditcards.chase.com/rewards-credit-cards/sapphire/reserve',
    applyUrl: 'https://creditcards.chase.com/a1/sapphirereserve/compare',
  },
  {
    id: 'chase-freedom-unlimited',
    name: 'Freedom Unlimited',
    issuer: 'Chase',
    network: 'visa',
    annual_fee_cents: 0,
    last_verified: '2025-01-03',
    baseEarning: '1.5%',
    valueType: 'cashback',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Travel (Chase Portal)', multiplier: 5, notes: 'Via Chase portal' },
      { category: 'Dining', multiplier: 3 },
      { category: 'Drugstores', multiplier: 3 },
      { category: 'All Other Purchases', multiplier: 1.5 },
    ],
    exclusions: [],
    highlights: [
      'No annual fee',
      '1.5% base rate on everything',
      'Good base card for Chase ecosystem',
    ],
    artwork: { kind: 'gradient', primary: '#1E3A5F', secondary: '#3D5A80', accent: '#98C1D9', pattern: 'standard' },
    foreign_tx_fee_percent: 3,
    learnMoreUrl: 'https://creditcards.chase.com/cash-back-credit-cards/freedom/unlimited',
    applyUrl: 'https://creditcards.chase.com/a1/freedomunlimited/compare',
  },
  {
    id: 'chase-freedom-flex',
    name: 'Freedom Flex',
    issuer: 'Chase',
    network: 'mastercard',
    annual_fee_cents: 0,
    last_verified: '2025-01-03',
    baseEarning: '1%',
    valueType: 'cashback',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Quarterly Categories', multiplier: 5, notes: 'Rotating categories, activation required', caps: 'Up to $1,500/quarter' },
      { category: 'Travel (Chase Portal)', multiplier: 5, notes: 'Via Chase portal' },
      { category: 'Dining', multiplier: 3 },
      { category: 'Drugstores', multiplier: 3 },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      'No annual fee',
      '5% rotating quarterly categories',
      'Must activate categories each quarter',
    ],
    artwork: { kind: 'gradient', primary: '#2E4057', secondary: '#4F6D7A', accent: '#88A0A8', pattern: 'standard' },
    foreign_tx_fee_percent: 3,
    learnMoreUrl: 'https://creditcards.chase.com/cash-back-credit-cards/freedom/flex',
    applyUrl: 'https://creditcards.chase.com/a1/freedomflex/compare',
  },
  {
    id: 'chase-ink-business-preferred',
    name: 'Ink Business Preferred',
    issuer: 'Chase',
    network: 'visa',
    annual_fee_cents: 9500,
    last_verified: '2025-01-03',
    baseEarning: '1x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Travel', multiplier: 3, caps: 'Up to $150,000/year combined' },
      { category: 'Shipping', multiplier: 3, caps: 'Up to $150,000/year combined' },
      { category: 'Internet/Phone/Cable', multiplier: 3, caps: 'Up to $150,000/year combined' },
      { category: 'Advertising', multiplier: 3, notes: 'Social media & search engines', caps: 'Up to $150,000/year combined' },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      'Great for business expenses',
      'Points transfer to travel partners',
      'No foreign transaction fees',
    ],
    artwork: { kind: 'gradient', primary: '#1A1F71', secondary: '#0D47A1', accent: '#1565C0', pattern: 'premium' },
    foreign_tx_fee_percent: 0,
    learnMoreUrl: 'https://creditcards.chase.com/business-credit-cards/ink/business-preferred',
    applyUrl: 'https://creditcards.chase.com/a1/inkbusinesspreferred/app',
  },
  {
    id: 'chase-ink-business-unlimited',
    name: 'Ink Business Unlimited',
    issuer: 'Chase',
    network: 'visa',
    annual_fee_cents: 0,
    last_verified: '2025-01-03',
    baseEarning: '1.5%',
    valueType: 'cashback',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'All Purchases', multiplier: 1.5, notes: 'Flat 1.5% unlimited cash back' },
    ],
    exclusions: [],
    highlights: [
      'No annual fee',
      'Simple flat rate on everything',
      'Good for business with varied spending',
    ],
    artwork: { kind: 'gradient', primary: '#1A3C6E', secondary: '#2D5A8E', accent: '#4A7DB8', pattern: 'standard' },
    foreign_tx_fee_percent: 3,
    learnMoreUrl: 'https://creditcards.chase.com/business-credit-cards/ink/unlimited',
    applyUrl: 'https://creditcards.chase.com/a1/inkbusinessunlimited/app',
  },
  {
    id: 'chase-united-explorer',
    name: 'United Explorer',
    issuer: 'Chase',
    network: 'visa',
    annual_fee_cents: 9500,
    last_verified: '2025-01-03',
    baseEarning: '1x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'United Purchases', multiplier: 2, notes: 'On United flights' },
      { category: 'Dining', multiplier: 2 },
      { category: 'Hotel', multiplier: 2, notes: 'Directly with hotels' },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      'First checked bag free',
      'Priority boarding',
      '2 United Club passes annually',
    ],
    artwork: { kind: 'gradient', primary: '#002244', secondary: '#0066CC', accent: '#4A90D9', pattern: 'standard' },
    foreign_tx_fee_percent: 0,
    learnMoreUrl: 'https://creditcards.chase.com/travel-credit-cards/united/united-explorer',
    applyUrl: 'https://creditcards.chase.com/a1/unitedexplorer/app',
  },
  {
    id: 'chase-southwest-rapid-rewards-plus',
    name: 'Southwest Rapid Rewards Plus',
    issuer: 'Chase',
    network: 'visa',
    annual_fee_cents: 6900,
    last_verified: '2025-01-03',
    baseEarning: '1x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Southwest Purchases', multiplier: 2, notes: 'On Southwest flights' },
      { category: 'Rapid Rewards Partners', multiplier: 2 },
      { category: 'Local Transit/Commuting', multiplier: 2 },
      { category: 'Internet/Phone/Cable', multiplier: 2 },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      '3,000 anniversary points',
      '25% back on inflight purchases',
      'Earn Companion Pass',
    ],
    artwork: { kind: 'gradient', primary: '#304CB2', secondary: '#FFBF27', accent: '#E01933', pattern: 'standard' },
    foreign_tx_fee_percent: 3,
    learnMoreUrl: 'https://creditcards.chase.com/travel-credit-cards/southwest/plus',
    applyUrl: 'https://creditcards.chase.com/a1/southwestplus/app',
  },

  // === CAPITAL ONE (5 cards) ===
  {
    id: 'capital-one-savor-one',
    name: 'SavorOne',
    issuer: 'Capital One',
    network: 'mastercard',
    annual_fee_cents: 0,
    last_verified: '2025-01-03',
    baseEarning: '1%',
    valueType: 'cashback',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Dining', multiplier: 3 },
      { category: 'Entertainment', multiplier: 3 },
      { category: 'Streaming', multiplier: 3 },
      { category: 'Grocery Stores', multiplier: 3, notes: 'Excludes wholesale clubs', exclusions: ['Costco', 'Sam\'s Club'] },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: ['Costco', 'Sam\'s Club', 'Wholesale clubs'],
    highlights: [
      'No annual fee',
      'No foreign transaction fees',
      'Great for dining and entertainment',
    ],
    artwork: { kind: 'gradient', primary: '#1A1A2E', secondary: '#16213E', accent: '#0F3460', pattern: 'standard' },
    foreign_tx_fee_percent: 0,
    learnMoreUrl: 'https://www.capitalone.com/credit-cards/savorone-dining-rewards/',
    applyUrl: 'https://www.capitalone.com/credit-cards/savorone-dining-rewards/',
  },
  {
    id: 'capital-one-venture',
    name: 'Venture',
    issuer: 'Capital One',
    network: 'visa',
    annual_fee_cents: 9500,
    last_verified: '2025-01-03',
    baseEarning: '2x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'All Purchases', multiplier: 2, notes: '2X miles on every purchase' },
    ],
    exclusions: [],
    highlights: [
      'Simple 2X on everything',
      'Miles transfer to 15+ partners',
      'No foreign transaction fees',
    ],
    artwork: { kind: 'gradient', primary: '#2D3436', secondary: '#636E72', accent: '#B2BEC3', pattern: 'standard' },
    foreign_tx_fee_percent: 0,
    learnMoreUrl: 'https://www.capitalone.com/credit-cards/venture/',
    applyUrl: 'https://www.capitalone.com/credit-cards/venture/',
  },
  {
    id: 'capital-one-venture-x',
    name: 'Venture X',
    issuer: 'Capital One',
    network: 'visa',
    annual_fee_cents: 39500,
    last_verified: '2025-01-03',
    baseEarning: '2x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Hotels (C1 Travel)', multiplier: 10, notes: 'Via Capital One Travel' },
      { category: 'Flights (C1 Travel)', multiplier: 5, notes: 'Via Capital One Travel' },
      { category: 'All Other Purchases', multiplier: 2 },
    ],
    exclusions: [],
    highlights: [
      '$300 annual travel credit',
      '10,000 bonus miles annually',
      'Priority Pass & Capital One lounges',
    ],
    artwork: { kind: 'gradient', primary: '#1A1A1A', secondary: '#333333', accent: '#4A4A4A', pattern: 'premium' },
    foreign_tx_fee_percent: 0,
    credits_summary: '$300 annual travel credit + 10,000 bonus miles',
    learnMoreUrl: 'https://www.capitalone.com/credit-cards/venture-x/',
    applyUrl: 'https://www.capitalone.com/credit-cards/venture-x/',
  },
  {
    id: 'capital-one-quicksilver',
    name: 'Quicksilver',
    issuer: 'Capital One',
    network: 'mastercard',
    annual_fee_cents: 0,
    last_verified: '2025-01-03',
    baseEarning: '1.5%',
    valueType: 'cashback',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'All Purchases', multiplier: 1.5, notes: 'Flat 1.5% cash back' },
    ],
    exclusions: [],
    highlights: [
      'No annual fee',
      'Simple 1.5% on everything',
      'No foreign transaction fees',
    ],
    artwork: { kind: 'gradient', primary: '#3D3D3D', secondary: '#5C5C5C', accent: '#7B7B7B', pattern: 'standard' },
    foreign_tx_fee_percent: 0,
    learnMoreUrl: 'https://www.capitalone.com/credit-cards/quicksilver/',
    applyUrl: 'https://www.capitalone.com/credit-cards/quicksilver/',
  },
  {
    id: 'capital-one-savor',
    name: 'Savor',
    issuer: 'Capital One',
    network: 'mastercard',
    annual_fee_cents: 9500,
    last_verified: '2025-01-03',
    baseEarning: '1%',
    valueType: 'cashback',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Dining', multiplier: 4 },
      { category: 'Entertainment', multiplier: 4 },
      { category: 'Streaming', multiplier: 4 },
      { category: 'Grocery Stores', multiplier: 3, exclusions: ['Costco', 'Sam\'s Club'] },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: ['Costco', 'Sam\'s Club'],
    highlights: [
      '4% on dining and entertainment',
      'No foreign transaction fees',
      'Strong for frequent diners',
    ],
    artwork: { kind: 'gradient', primary: '#1A1A2E', secondary: '#0F3460', accent: '#E94560', pattern: 'premium' },
    foreign_tx_fee_percent: 0,
    learnMoreUrl: 'https://www.capitalone.com/credit-cards/savor-dining-rewards/',
    applyUrl: 'https://www.capitalone.com/credit-cards/savor-dining-rewards/',
  },

  // === CITI (5 cards) ===
  {
    id: 'citi-double-cash',
    name: 'Double Cash',
    issuer: 'Citi',
    network: 'mastercard',
    annual_fee_cents: 0,
    last_verified: '2025-01-03',
    baseEarning: '2%',
    valueType: 'cashback',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'All Purchases', multiplier: 2, notes: '1% when you buy, 1% when you pay' },
    ],
    exclusions: [],
    highlights: [
      'No annual fee',
      'Simple 2% on everything',
      'Must pay bill to earn full 2%',
    ],
    artwork: { kind: 'gradient', primary: '#003366', secondary: '#0055A5', accent: '#0077CC', pattern: 'standard' },
    foreign_tx_fee_percent: 3,
    learnMoreUrl: 'https://www.citi.com/credit-cards/citi-double-cash-credit-card',
    applyUrl: 'https://www.citi.com/credit-cards/citi-double-cash-credit-card',
  },
  {
    id: 'citi-custom-cash',
    name: 'Custom Cash',
    issuer: 'Citi',
    network: 'mastercard',
    annual_fee_cents: 0,
    last_verified: '2025-01-03',
    baseEarning: '1%',
    valueType: 'cashback',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Top Eligible Category', multiplier: 5, notes: 'Auto-selected based on spending', caps: 'Up to $500/billing cycle' },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      'No annual fee',
      'Automatic category selection',
      'Great for focused spending',
    ],
    artwork: { kind: 'gradient', primary: '#1A365D', secondary: '#2C5282', accent: '#4299E1', pattern: 'standard' },
    foreign_tx_fee_percent: 3,
    learnMoreUrl: 'https://www.citi.com/credit-cards/citi-custom-cash-credit-card',
    applyUrl: 'https://www.citi.com/credit-cards/citi-custom-cash-credit-card',
  },
  {
    id: 'citi-premier',
    name: 'Premier',
    issuer: 'Citi',
    network: 'mastercard',
    annual_fee_cents: 9500,
    last_verified: '2025-01-03',
    baseEarning: '1x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Restaurants', multiplier: 3 },
      { category: 'Supermarkets', multiplier: 3 },
      { category: 'Gas Stations', multiplier: 3 },
      { category: 'Air Travel', multiplier: 3 },
      { category: 'Hotels', multiplier: 3 },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      '3X on restaurants, grocery, gas, travel',
      'Transfer to airline partners',
      'No foreign transaction fees',
    ],
    artwork: { kind: 'gradient', primary: '#003366', secondary: '#004488', accent: '#0066CC', pattern: 'premium' },
    foreign_tx_fee_percent: 0,
    learnMoreUrl: 'https://www.citi.com/credit-cards/citi-premier-credit-card',
    applyUrl: 'https://www.citi.com/credit-cards/citi-premier-credit-card',
  },
  {
    id: 'citi-rewards-plus',
    name: 'Rewards+',
    issuer: 'Citi',
    network: 'mastercard',
    annual_fee_cents: 0,
    last_verified: '2025-01-03',
    baseEarning: '1x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Supermarkets', multiplier: 2, caps: 'Up to $6,000/year, then 1X' },
      { category: 'Gas Stations', multiplier: 2, caps: 'Up to $6,000/year, then 1X' },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      'No annual fee',
      'Round up to nearest 10 points',
      '10% points back on first 100K redeemed/year',
    ],
    artwork: { kind: 'gradient', primary: '#003366', secondary: '#0055A5', accent: '#4A90D9', pattern: 'standard' },
    foreign_tx_fee_percent: 3,
    learnMoreUrl: 'https://www.citi.com/credit-cards/citi-rewards-plus-credit-card',
    applyUrl: 'https://www.citi.com/credit-cards/citi-rewards-plus-credit-card',
  },
  {
    id: 'citi-strata-premier',
    name: 'Strata Premier',
    issuer: 'Citi',
    network: 'mastercard',
    annual_fee_cents: 9500,
    last_verified: '2025-01-03',
    baseEarning: '1x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Air Travel & Hotels', multiplier: 10, notes: 'Via thankyou.com' },
      { category: 'Restaurants', multiplier: 3 },
      { category: 'Supermarkets', multiplier: 3 },
      { category: 'Gas Stations', multiplier: 3 },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      '10X on travel booked through Citi',
      'Annual hotel savings benefit',
      'No foreign transaction fees',
    ],
    artwork: { kind: 'gradient', primary: '#1A1F4E', secondary: '#2A3366', accent: '#4A5588', pattern: 'premium' },
    foreign_tx_fee_percent: 0,
    learnMoreUrl: 'https://www.citi.com/credit-cards/citi-strata-premier-credit-card',
    applyUrl: 'https://www.citi.com/credit-cards/citi-strata-premier-credit-card',
  },

  // === DISCOVER (3 cards) ===
  {
    id: 'discover-it',
    name: 'Discover it Cash Back',
    issuer: 'Discover',
    network: 'discover',
    annual_fee_cents: 0,
    last_verified: '2025-01-03',
    baseEarning: '1%',
    valueType: 'cashback',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Quarterly Categories', multiplier: 5, notes: 'Rotating categories, activation required', caps: 'Up to $1,500/quarter' },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      'No annual fee',
      'Cashback Match first year',
      '5% rotating quarterly categories',
    ],
    artwork: { kind: 'gradient', primary: '#FF6600', secondary: '#FF8533', accent: '#FFA366', pattern: 'standard' },
    foreign_tx_fee_percent: 0,
    learnMoreUrl: 'https://www.discover.com/credit-cards/cash-back/it-card.html',
    applyUrl: 'https://www.discover.com/credit-cards/cash-back/it-card.html',
  },
  {
    id: 'discover-it-miles',
    name: 'Discover it Miles',
    issuer: 'Discover',
    network: 'discover',
    annual_fee_cents: 0,
    last_verified: '2025-01-03',
    baseEarning: '1.5x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'All Purchases', multiplier: 1.5, notes: '1.5X miles on every purchase' },
    ],
    exclusions: [],
    highlights: [
      'No annual fee',
      'Miles Match first year',
      'Redeem for any travel purchase',
    ],
    artwork: { kind: 'gradient', primary: '#FF6600', secondary: '#FF8533', accent: '#0066CC', pattern: 'standard' },
    foreign_tx_fee_percent: 0,
    learnMoreUrl: 'https://www.discover.com/credit-cards/travel/it-miles.html',
    applyUrl: 'https://www.discover.com/credit-cards/travel/it-miles.html',
  },
  {
    id: 'discover-it-student',
    name: 'Discover it Student',
    issuer: 'Discover',
    network: 'discover',
    annual_fee_cents: 0,
    last_verified: '2025-01-03',
    baseEarning: '1%',
    valueType: 'cashback',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Quarterly Categories', multiplier: 5, notes: 'Rotating categories, activation required', caps: 'Up to $1,500/quarter' },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      'No annual fee',
      'Good grades reward',
      'Cashback Match first year',
    ],
    artwork: { kind: 'gradient', primary: '#E65C00', secondary: '#F08030', accent: '#FFA060', pattern: 'standard' },
    foreign_tx_fee_percent: 0,
    learnMoreUrl: 'https://www.discover.com/credit-cards/student/',
    applyUrl: 'https://www.discover.com/credit-cards/student/',
  },

  // === WELLS FARGO (3 cards) ===
  {
    id: 'wells-fargo-active-cash',
    name: 'Active Cash',
    issuer: 'Wells Fargo',
    network: 'visa',
    annual_fee_cents: 0,
    last_verified: '2025-01-03',
    baseEarning: '2%',
    valueType: 'cashback',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'All Purchases', multiplier: 2, notes: 'Flat 2% cash back' },
    ],
    exclusions: [],
    highlights: [
      'No annual fee',
      'Simple 2% on everything',
      'No activation required',
    ],
    artwork: { kind: 'gradient', primary: '#C41230', secondary: '#D32F2F', accent: '#FFEB3B', pattern: 'standard' },
    foreign_tx_fee_percent: 3,
    learnMoreUrl: 'https://www.wellsfargo.com/credit-cards/active-cash-card/',
    applyUrl: 'https://www.wellsfargo.com/credit-cards/active-cash-card/',
  },
  {
    id: 'wells-fargo-autograph',
    name: 'Autograph',
    issuer: 'Wells Fargo',
    network: 'visa',
    annual_fee_cents: 0,
    last_verified: '2025-01-03',
    baseEarning: '1x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Restaurants', multiplier: 3 },
      { category: 'Travel', multiplier: 3 },
      { category: 'Gas Stations', multiplier: 3 },
      { category: 'Transit', multiplier: 3 },
      { category: 'Streaming', multiplier: 3 },
      { category: 'Phone Plans', multiplier: 3 },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      'No annual fee',
      '3X on 6 popular categories',
      'No foreign transaction fees',
    ],
    artwork: { kind: 'gradient', primary: '#B71C1C', secondary: '#D32F2F', accent: '#FFD600', pattern: 'standard' },
    foreign_tx_fee_percent: 0,
    learnMoreUrl: 'https://www.wellsfargo.com/credit-cards/autograph-card/',
    applyUrl: 'https://www.wellsfargo.com/credit-cards/autograph-card/',
  },
  {
    id: 'wells-fargo-autograph-journey',
    name: 'Autograph Journey',
    issuer: 'Wells Fargo',
    network: 'visa',
    annual_fee_cents: 9500,
    last_verified: '2025-01-03',
    baseEarning: '1x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Hotels', multiplier: 5 },
      { category: 'Air Travel', multiplier: 4 },
      { category: 'Restaurants', multiplier: 3 },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      'Transfer to airline partners',
      '$50 annual Autograph benefit',
      'No foreign transaction fees',
    ],
    artwork: { kind: 'gradient', primary: '#8B0000', secondary: '#B22222', accent: '#FFD700', pattern: 'premium' },
    foreign_tx_fee_percent: 0,
    credits_summary: '$50 annual Autograph benefit',
    learnMoreUrl: 'https://www.wellsfargo.com/credit-cards/autograph-journey/',
    applyUrl: 'https://www.wellsfargo.com/credit-cards/autograph-journey/',
  },

  // === BANK OF AMERICA (3 cards) ===
  {
    id: 'bofa-customized-cash',
    name: 'Customized Cash Rewards',
    issuer: 'Bank of America',
    network: 'visa',
    annual_fee_cents: 0,
    last_verified: '2025-01-03',
    baseEarning: '1%',
    valueType: 'cashback',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Choice Category', multiplier: 3, notes: 'Gas, online shopping, dining, travel, drug stores, or home improvement', caps: 'Up to $2,500/quarter' },
      { category: 'Grocery Stores', multiplier: 2, notes: 'And wholesale clubs', caps: 'Up to $2,500/quarter' },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      'No annual fee',
      'Choose your 3% category',
      'Preferred Rewards bonus up to 75%',
    ],
    artwork: { kind: 'gradient', primary: '#012169', secondary: '#0033A0', accent: '#E31837', pattern: 'standard' },
    foreign_tx_fee_percent: 3,
    learnMoreUrl: 'https://www.bankofamerica.com/credit-cards/products/cash-back-credit-card/',
    applyUrl: 'https://www.bankofamerica.com/credit-cards/products/cash-back-credit-card/',
  },
  {
    id: 'bofa-unlimited-cash',
    name: 'Unlimited Cash Rewards',
    issuer: 'Bank of America',
    network: 'visa',
    annual_fee_cents: 0,
    last_verified: '2025-01-03',
    baseEarning: '1.5%',
    valueType: 'cashback',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'All Purchases', multiplier: 1.5, notes: 'Flat 1.5% unlimited cash back' },
    ],
    exclusions: [],
    highlights: [
      'No annual fee',
      'Simple 1.5% on everything',
      'Preferred Rewards bonus up to 75%',
    ],
    artwork: { kind: 'gradient', primary: '#012169', secondary: '#004B87', accent: '#E31837', pattern: 'standard' },
    foreign_tx_fee_percent: 3,
    learnMoreUrl: 'https://www.bankofamerica.com/credit-cards/products/unlimited-cash-back-credit-card/',
    applyUrl: 'https://www.bankofamerica.com/credit-cards/products/unlimited-cash-back-credit-card/',
  },
  {
    id: 'bofa-premium-rewards',
    name: 'Premium Rewards',
    issuer: 'Bank of America',
    network: 'visa',
    annual_fee_cents: 9500,
    last_verified: '2025-01-03',
    baseEarning: '1.5x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Travel', multiplier: 2 },
      { category: 'Dining', multiplier: 2 },
      { category: 'All Other Purchases', multiplier: 1.5 },
    ],
    exclusions: [],
    highlights: [
      '$100 annual airline incidentals credit',
      'No foreign transaction fees',
      'Preferred Rewards bonus up to 75%',
    ],
    artwork: { kind: 'gradient', primary: '#012169', secondary: '#0033A0', accent: '#FFD700', pattern: 'premium' },
    foreign_tx_fee_percent: 0,
    credits_summary: '$100 annual airline credit',
    learnMoreUrl: 'https://www.bankofamerica.com/credit-cards/products/premium-rewards-credit-card/',
    applyUrl: 'https://www.bankofamerica.com/credit-cards/products/premium-rewards-credit-card/',
  },

  // === U.S. BANK (4 cards) ===
  {
    id: 'usbank-altitude-go',
    name: 'Altitude Go',
    issuer: 'U.S. Bank',
    network: 'visa',
    annual_fee_cents: 0,
    last_verified: '2025-01-03',
    baseEarning: '1x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Dining', multiplier: 4 },
      { category: 'Grocery Stores', multiplier: 2 },
      { category: 'Streaming Services', multiplier: 2 },
      { category: 'Gas Stations', multiplier: 2 },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      'No annual fee',
      '4X dining is competitive',
      'No foreign transaction fees',
    ],
    artwork: { kind: 'gradient', primary: '#002868', secondary: '#0046AD', accent: '#BF0A30', pattern: 'standard' },
    foreign_tx_fee_percent: 0,
    learnMoreUrl: 'https://www.usbank.com/credit-cards/altitude-go-visa-signature-credit-card.html',
    applyUrl: 'https://www.usbank.com/credit-cards/altitude-go-visa-signature-credit-card.html',
  },
  {
    id: 'usbank-cash-plus',
    name: 'Cash+',
    issuer: 'U.S. Bank',
    network: 'visa',
    annual_fee_cents: 0,
    last_verified: '2025-01-03',
    baseEarning: '1%',
    valueType: 'cashback',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Two Choice Categories', multiplier: 5, notes: 'Select 2 categories each quarter', caps: 'Up to $2,000/quarter combined' },
      { category: 'Grocery & Gas', multiplier: 2 },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      'No annual fee',
      'Choose your 5% categories',
      'Utilities can be a 5% category',
    ],
    artwork: { kind: 'gradient', primary: '#003B70', secondary: '#005CAA', accent: '#7EC8E3', pattern: 'standard' },
    foreign_tx_fee_percent: 3,
    learnMoreUrl: 'https://www.usbank.com/credit-cards/cash-plus-visa-signature-credit-card.html',
    applyUrl: 'https://www.usbank.com/credit-cards/cash-plus-visa-signature-credit-card.html',
  },
  {
    id: 'usbank-altitude-reserve',
    name: 'Altitude Reserve',
    issuer: 'U.S. Bank',
    network: 'visa',
    annual_fee_cents: 40000,
    last_verified: '2025-01-03',
    baseEarning: '1x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Travel', multiplier: 3 },
      { category: 'Mobile Wallet Purchases', multiplier: 3, notes: 'Apple Pay, Google Pay, Samsung Pay' },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      '$325 annual travel credit',
      'Priority Pass membership',
      'Points worth 50% more for travel',
    ],
    artwork: { kind: 'gradient', primary: '#1A1A1A', secondary: '#333333', accent: '#002868', pattern: 'premium' },
    foreign_tx_fee_percent: 0,
    credits_summary: '$325 annual travel credit',
    learnMoreUrl: 'https://www.usbank.com/credit-cards/altitude-reserve-visa-infinite-credit-card.html',
    applyUrl: 'https://www.usbank.com/credit-cards/altitude-reserve-visa-infinite-credit-card.html',
  },
  {
    id: 'usbank-altitude-connect',
    name: 'Altitude Connect',
    issuer: 'U.S. Bank',
    network: 'visa',
    annual_fee_cents: 9500,
    last_verified: '2025-01-03',
    baseEarning: '1x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Hotels', multiplier: 5, notes: 'Booked via Altitude Rewards Center' },
      { category: 'Rental Cars', multiplier: 5, notes: 'Booked via Altitude Rewards Center' },
      { category: 'Dining', multiplier: 4 },
      { category: 'Gas/EV Charging', multiplier: 2 },
      { category: 'Grocery Stores', multiplier: 2 },
      { category: 'Streaming', multiplier: 2 },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      '$30 annual streaming credit',
      'No foreign transaction fees',
      'Transfer to airline partners',
    ],
    artwork: { kind: 'gradient', primary: '#002868', secondary: '#0046AD', accent: '#4A7DC6', pattern: 'standard' },
    foreign_tx_fee_percent: 0,
    credits_summary: '$30 annual streaming credit',
    learnMoreUrl: 'https://www.usbank.com/credit-cards/altitude-connect-visa-signature-credit-card.html',
    applyUrl: 'https://www.usbank.com/credit-cards/altitude-connect-visa-signature-credit-card.html',
  },

  // === APPLE (1 card) ===
  {
    id: 'apple-card',
    name: 'Apple Card',
    issuer: 'Apple',
    network: 'mastercard',
    annual_fee_cents: 0,
    last_verified: '2025-01-03',
    baseEarning: '1%',
    valueType: 'cashback',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Apple Purchases', multiplier: 3, notes: 'Apple Pay at Apple' },
      { category: 'Apple Pay Purchases', multiplier: 2, notes: 'Using Apple Pay anywhere' },
      { category: 'Physical Card', multiplier: 1, notes: 'Using the titanium card' },
    ],
    exclusions: [],
    highlights: [
      'No annual fee',
      'No foreign transaction fees',
      'Daily Cash rewards',
      'Clean titanium design',
    ],
    artwork: { kind: 'gradient', primary: '#F5F5F7', secondary: '#FFFFFF', accent: '#E8E8ED', pattern: 'minimal' },
    foreign_tx_fee_percent: 0,
    learnMoreUrl: 'https://www.apple.com/apple-card/',
    applyUrl: 'https://www.apple.com/apple-card/',
  },

  // === BILT (1 card) ===
  {
    id: 'bilt-mastercard',
    name: 'Bilt Mastercard',
    issuer: 'Bilt',
    network: 'mastercard',
    annual_fee_cents: 0,
    last_verified: '2025-01-03',
    baseEarning: '1x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'Rent Payments', multiplier: 1, notes: 'No fee to pay rent with card' },
      { category: 'Dining', multiplier: 3 },
      { category: 'Travel', multiplier: 2 },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      'No annual fee',
      'Earn points on rent',
      'Transfer to airline/hotel partners',
      'Must make 5 transactions/month to earn',
    ],
    artwork: { kind: 'gradient', primary: '#1A1A1A', secondary: '#2D2D2D', accent: '#404040', pattern: 'minimal' },
    foreign_tx_fee_percent: 0,
    learnMoreUrl: 'https://www.bilt.com/credit-card',
    applyUrl: 'https://www.bilt.com/credit-card',
  },

  // === BARCLAYS (2 cards) ===
  {
    id: 'barclays-view',
    name: 'Barclays View',
    issuer: 'Barclays',
    network: 'mastercard',
    annual_fee_cents: 0,
    last_verified: '2025-01-03',
    baseEarning: '1%',
    valueType: 'cashback',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'All Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      'No annual fee',
      'View your FICO score',
      'Cell phone protection',
    ],
    artwork: { kind: 'gradient', primary: '#00AEEF', secondary: '#0082C8', accent: '#005691', pattern: 'standard' },
    foreign_tx_fee_percent: 0,
    learnMoreUrl: 'https://cards.barclaycardus.com/banking/cards/barclays-view-mastercard/',
    applyUrl: 'https://cards.barclaycardus.com/banking/cards/barclays-view-mastercard/',
  },
  {
    id: 'barclays-aadvantage-aviator-red',
    name: 'AAdvantage Aviator Red',
    issuer: 'Barclays',
    network: 'mastercard',
    annual_fee_cents: 9900,
    last_verified: '2025-01-03',
    baseEarning: '1x',
    valueType: 'points',
    dataConfidence: 'high',
    needsVerification: false,
    rewards: [
      { category: 'American Airlines', multiplier: 2, notes: 'On eligible AA purchases' },
      { category: 'All Other Purchases', multiplier: 1 },
    ],
    exclusions: [],
    highlights: [
      'First checked bag free on AA',
      'Preferred boarding',
      '25% savings on inflight purchases',
    ],
    artwork: { kind: 'gradient', primary: '#C8102E', secondary: '#001489', accent: '#A9A9A9', pattern: 'standard' },
    foreign_tx_fee_percent: 0,
    learnMoreUrl: 'https://cards.barclaycardus.com/banking/cards/aadvantage-aviator-red-world-elite-mastercard/',
    applyUrl: 'https://cards.barclaycardus.com/banking/cards/aadvantage-aviator-red-world-elite-mastercard/',
  },
];

// Network display labels
export const networkLabels: Record<CardNetwork, string> = {
  visa: 'Visa',
  mastercard: 'Mastercard',
  amex: 'Amex',
  discover: 'Discover',
};

// Get card by ID
export function getCardById(id: string): Card | undefined {
  return cardCatalog.find(card => card.id === id);
}

// Get cards by issuer
export function getCardsByIssuer(issuer: string): Card[] {
  return cardCatalog.filter(card => card.issuer === issuer);
}

// Get all unique issuers
export function getAllIssuers(): string[] {
  return [...new Set(cardCatalog.map(card => card.issuer))].sort();
}

// Format annual fee
export function formatAnnualFee(cents: number | null): string {
  if (cents === null) return 'Verify';
  if (cents === 0) return 'No annual fee';
  return `$${cents / 100}/year`;
}

// Format multiplier with category
export function formatReward(reward: CardReward): string {
  return `${reward.multiplier}x ${reward.category}`;
}

// Get reward summary string
export function getRewardSummary(rewards: CardReward[]): string {
  return rewards
    .filter(r => r.multiplier > 1)
    .slice(0, 3)
    .map(r => formatReward(r))
    .join(', ');
}

// Get cards by confidence level
export function getCardsByConfidence(confidence: DataConfidence): Card[] {
  return cardCatalog.filter(card => card.dataConfidence === confidence);
}

// Get cards needing verification
export function getCardsNeedingVerification(): Card[] {
  return cardCatalog.filter(card => card.needsVerification);
}
